### ISSUE TITLE
Page blanche comportant juste le nom de l'analyse

### ISSUE THREAD

**Issue by ThibaudVerny** [NikaAb/BCR_intraclonal_diversity#14]
Après avoir affiché un message d'erreur : "Sorry, there is no result. There must have been a problem during the analysis. " ViCoD sort une page blanche avec simplement le nom de l'analyse ainsi que les onglets classiques de la page d'accueil de ViCoD
![image](https://user-images.githubusercontent.com/65277508/118943731-3014e800-b954-11eb-96db-a540de4c014f.png)

**Comment by ThibaudVerny** [comment]
Bug corrigé, merci !

**Comment by LucileJeusset** [comment]
Merci @ThibaudVerny, tu as été plus rapide que moi je n'ai pas eu le temps de te répondre ^^
Oui je viens de corriger ça. J'ai relancé toutes tes analyses qui ne fonctionnaient pas. Tu peux réutiliser les liens de tes précédentes analyses.
